In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from sklearn.datasets import load_boston

In [3]:
boston=load_boston()

In [4]:
dataset=pd.DataFrame(boston.data,columns=boston.feature_names)

In [5]:
dataset['Price']=boston.target

In [6]:
X=dataset.iloc[:,:-1]
y=dataset.iloc[:,-1]

In [8]:
##Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [9]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [10]:
X_train=scaler.fit_transform(X_train)

In [11]:
X_test=scaler.transform(X_test)

In [12]:
import pickle
pickle.dump(scaler,open('scaling.pkl','wb'))

In [13]:
from sklearn.linear_model import LinearRegression

In [14]:
regression=LinearRegression()

In [15]:
regression.fit(X_train,y_train)

LinearRegression()

In [16]:
reg_pred=regression.predict(X_test)

In [17]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

print(mean_absolute_error(y_test,reg_pred))
print(mean_squared_error(y_test,reg_pred))
print(np.sqrt(mean_squared_error(y_test,reg_pred)))

3.162709871457404
21.517444231177194
4.638689926172819


In [18]:
from sklearn.metrics import r2_score
score=r2_score(y_test,reg_pred)
print(score)

0.7112260057484934


In [19]:

#display adjusted R-squared
1 - (1-score)*(len(y_test)-1)/(len(y_test)-X_test.shape[1]-1)

0.6840226584639312

In [20]:
boston.data[0].reshape(1,-1)

array([[6.320e-03, 1.800e+01, 2.310e+00, 0.000e+00, 5.380e-01, 6.575e+00,
        6.520e+01, 4.090e+00, 1.000e+00, 2.960e+02, 1.530e+01, 3.969e+02,
        4.980e+00]])

In [21]:
scaler.transform(boston.data[0].reshape(1,-1))

array([[-0.41709233,  0.29216419, -1.27338003, -0.28154625, -0.16513629,
         0.34715902, -0.13030059,  0.15267164, -0.97798895, -0.66777595,
        -1.32142483,  0.42854113, -1.04769976]])

In [22]:
regression.predict(scaler.transform(boston.data[0].reshape(1,-1)))

array([30.08649576])

In [23]:
pickle.dump(regression,open('regmodel.pkl','wb'))